// Annual REAL US returns 1871–2024, embedded at build time (never fetched at runtime).
// Generated by scripts/generateHistoricalData.mjs from the Shiller dataset — see that
// script for methodology and sources.

import raw from './historicalReturns.json';

export interface HistoricalYear {
  year: number;
  /** Real S&P composite total return (Jan→Jan, dividends reinvested). */
  stock: number;
  /** Real 10-year Treasury total return (constant-maturity approximation). */
  bond: number;
  /** CPI inflation (Jan→Jan). */
  inflation: number;
}

export const HISTORICAL: HistoricalYear[] = raw;
export const FIRST_HISTORICAL_YEAR = HISTORICAL[0].year;
export const LAST_HISTORICAL_YEAR = HISTORICAL[HISTORICAL.length - 1].year;
